version: '3.9'
services:
  hue:
    build: .
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/data/minihue.sqlite
    volumes:
      - ./.data:/data
